DATA SEGMENT
    STRING DB "ChenAO HelLo0"
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA

START:
    MOV AX,DATA
    MOV DS,AX
    XOR AX,AX

    MOV BX,OFFSET STRING -1
AGAIN:
    INC BX
    CMP BYTE PTR[BX],"0"
    JE OVER

    CMP BYTE PTR[BX],"A"
    JB AGAIN
    CMP BYTE PTR[BX],"Z"
    JA AGAIN
    OR BYTE PTR[BX],20H
    JMP AGAIN
OVER:
    MOV AH,4CH
    INT 21H
CODE ENDS
END START
