DATA SEGMENT
    A DB 'AAAAA'
    B DB 'BBBBB'
    D DB 'CCCCC'
    DB '$'
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA

START:
    MOV AX,DATA
    MOV DS,AX
    XOR AX,AX

    MOV CX,5
    LEA SI,A
    LEA DI,B
AGAIN1:
    MOV AL,BYTE PTR [SI]
    MOV AH,BYTE PTR [DI]
    MOV BYTE PTR [SI],AH
    MOV BYTE PTR [DI],AL
    INC SI
    INC DI
    LOOP AGAIN1

    MOV CX,5
    LEA SI,A
    LEA DI,D
AGAIN2:
    MOV AL,BYTE PTR [SI]
    MOV AH,BYTE PTR [DI]
    MOV BYTE PTR [SI],AH
    MOV BYTE PTR [DI],AL
    INC SI
    INC DI
    LOOP AGAIN2

    LEA DX,A
    MOV AH,09H
    INT 21H

    MOV AH,4CH
    INT 21H
CODE ENDS
END START